spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/blackberryDB?allowPublicKeyRetrieval=true
    username: admin_bby
    password: bby2023
  sql:
    init:
      mode: always
  initialization-mode: always

management:
  endpoints:
    web:
      exposure:
        include: health
